### ISSUE TITLE
notes about your charm

### ISSUE THREAD

**Issue by merlijn-sebrechts** [LeandroOrdonez/superset#1]
https://github.com/LeandroOrdonez/superset/blob/master/reactive/superset.py#L13

- It's best to only use python3. `python-pip` installs pip for python2 packages. Use `python3-pip` same for `python3-dev` etc.
- Specify the packages using the layer options seen here: https://github.com/IBCNServices/layer-jupyter-notebook/blob/c89d32cf880ff85806a61a535ecb483ed35150cb/layer.yaml. Then you can remove this entire `setup` handler. The apt layer does the installation for you.

https://github.com/LeandroOrdonez/superset/blob/master/reactive/superset.py#L29

- `pip install` will install the python2 version, use `pip3 install`

https://github.com/LeandroOrdonez/superset/blob/master/reactive/superset.py#L34

- `check_call` creates a child process and then executes that command in the child process. Running `    subprocess.check_call(['su', '-', 'ubuntu'])` will change the user in the child process, not in the parent process.

I'd also recommend to just drop the virtualenv stuff for now. It will just make stuff more complicated.

**Comment by LeandroOrdonez** [comment]
@galgalesh It's working now :) maybe you can have a look at it and tell me what you think.
There are still some features that I have to work on, like an interface for it to connect with other stores different from SQLite.

**Comment by merlijn-sebrechts** [comment]
any reason this is still present? 

```python

    hookenv.log('Switching to user ubuntu')
    subprocess.check_call(['su', '-', 'ubuntu'])
    hookenv.log('whoami: %s' % subprocess.check_output(['whoami']).strip())
    hookenv.log('cat /etc/passwd | grep ubuntu: %s' % subprocess.check_output('cat /etc/passwd | grep ubuntu', shell=True).strip())
    hookenv.log('cwd: %s' % os.getcwd())
```

**Comment by merlijn-sebrechts** [comment]
I put the repo in ibcnservices and gave you push access. You can remove this repo and switch to that one.

https://github.com/IBCNServices/layer-superset

`git remote remove origin`
`git remote add origin https://github.com/IBCNServices/layer-superset`

**Comment by LeandroOrdonez** [comment]
Ok thanks! and regarding those lines, I'll remove them.
